[package]
name = "auto_hot_reload_lib"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
hot_reload_examples = { path = ".." } # example_lib
hot_reload = { path = "../..", optional = true }

[features]
default = ["hot_reload"]
hot_reload = ["dep:hot_reload"]
